info:
  app:
    name: "@project.name@"
    description: "@project.description@"
    version: "@project.version@"
server:
  port: 9604
spring:
  application:
    name: consul-demo-02
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      config:
        enabled: true
        format: yaml
        prefix: config
        default-context: application
        data-key: data
        profile-separator: '::'
      discovery:
        service-name: consul-demo-02
        prefer-ip-address: true
        instance-id: ${spring.application.name}-${spring.cloud.client.ip-address}-${server.port}
        # 健康检查失败多长时间后，取消注册
        health-check-critical-timeout: 30s